apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sbv67fljz-java-springboot-gitops-repository
spec:
  url: https://github.com/tnevrlka-rhtap/sbv67fljz-java-springboot-gitops